# Generated by Django 5.1.3 on 2024-12-13 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0005_alter_classe_nom_alter_etudiant_nom'),
    ]

    operations = [
        migrations.AlterField(
            model_name='classe',
            name='nom',
            field=models.CharField(max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='etudiant',
            name='nom',
            field=models.CharField(max_length=20),
        ),
        migrations.AddIndex(
            model_name='classe',
            index=models.Index(fields=['nom'], name='classe_nom_index'),
        ),
        migrations.AddIndex(
            model_name='etudiant',
            index=models.Index(fields=['classe'], name='etudiant_classe_index'),
        ),
        migrations.AddIndex(
            model_name='etudiant',
            index=models.Index(fields=['nom', 'email'], name='etudiant_nom_email_index'),
        ),
    ]
