# Generated by Django 5.1.3 on 2024-12-13 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0006_alter_classe_nom_alter_etudiant_nom_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='classe',
            name='classe_nom_index',
        ),
        migrations.AlterField(
            model_name='classe',
            name='nom',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
