# Generated by Django 5.1.3 on 2024-12-13 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('student_management_app', '0007_remove_classe_classe_nom_index_alter_classe_nom'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='etudiant',
            name='etudiant_classe_index',
        ),
        migrations.RemoveIndex(
            model_name='etudiant',
            name='etudiant_nom_email_index',
        ),
        migrations.AlterField(
            model_name='classe',
            name='nom',
            field=models.CharField(max_length=20, unique=True),
        ),
    ]
